apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: tutorial
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: skuser01.azurecr.io/payment:v1
          ports:
            - containerPort: 8080
